//
// Created by LiuQiang on 2024/9/22.
//

#ifndef HANDBOOK_FOR_ROBOT_BEGINNERS_TINYURDF_CONFIG_H
#define HANDBOOK_FOR_ROBOT_BEGINNERS_TINYURDF_CONFIG_H

#define USE_KDL

#endif // HANDBOOK_FOR_ROBOT_BEGINNERS_TINYURDF_CONFIG_H
