<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="SCARA">

<xacro:property name="base_height" value="0.6" />
<xacro:property name="l1" value="0.5" />
<xacro:property name="l2" value="0.5" />
<xacro:property name="l3" value="0.2" />
<xacro:property name="l4" value="0.4" />
<xacro:property name="l0" value="0.4" />

<xacro:property name="m1" value="6.5" />
<xacro:property name="m2" value="3.5" />
<xacro:property name="m3" value="2.5" />
<xacro:property name="m4" value="1.5" />


<xacro:property name="m1" value="6.5" />

<xacro:property name="PI" value="3.1415" />
<xacro:property name="lb" value="${-PI}" />
<xacro:property name="ub" value="${PI}" />


  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="green">
    <color rgba="0 1 0 1"/>
  </material>

  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

  <link name="world"/>
  <joint name="arm_to_world_fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>


  <link name="base_link">
   <inertial>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <mass value="0"/>
     <inertia ixx="0"  ixy="0"  ixz="0" iyy="0" iyz="0" izz="0" />
   </inertial>


    <visual>
      <geometry>
	      <cylinder length="${base_height}" radius="0.15"/>
      </geometry>
    <origin rpy="0 0 0" xyz="0 0 ${base_height/2}"/>
      <material name="blue"/>
    </visual>
  </link>

  <link name="link_1">
   <inertial>
     <origin xyz="0 ${l1/2} 0" rpy="0 0 0"/>
     <mass value="${m1}"/>
     <inertia ixx="1"  ixy="0"  ixz="0" iyy="1" iyz="0" izz="1" />
   </inertial>
    <visual>
      <geometry>
	      <cylinder length="${l1}" radius="0.1"/>
      </geometry>
      <material name="white"/>
      <origin rpy="${-PI/2} 0 0" xyz="0 ${l1/2} 0"/>
    </visual>
  </link>

  <joint name="joint_1" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${lb}" upper="${ub}" velocity="0.5"/>
    <origin rpy="0 0 0" xyz="0 0 ${base_height}"/>
    <parent link="base_link"/>
    <child link="link_1"/>
  </joint>

  <link name="link_2">
   <inertial>
     <origin xyz="0 ${l2/2} 0" rpy="0 0 0"/>
     <mass value="${m2}"/>
     <inertia ixx="1"  ixy="0"  ixz="0" iyy="1" iyz="0" izz="1" />
   </inertial>
    <visual>
      <geometry>
	      <cylinder length="${l2}" radius="0.1"/>
      </geometry>
      <material name="red"/>
      <origin rpy="${-PI/2} 0 0" xyz="0 ${l2/2} 0"/>
    </visual>
  </link>

  <joint name="joint_2" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${lb}" upper="${ub}" velocity="0.5"/>
    <parent link="link_1"/>
    <child link="link_2"/>
    <origin xyz="0 ${l1} 0 "/>
  </joint>

  <link name="link_3">
   <inertial>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <mass value="${m3}"/>
     <inertia ixx="1"  ixy="0"  ixz="0" iyy="1" iyz="0" izz="1" />
   </inertial>
    <visual>
      <geometry>
	      <cylinder length="${l3}" radius="0.1"/>
      </geometry>
      <material name="white"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
  </link>

  <joint name="joint_3" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${lb}" upper="${ub}" velocity="0.5"/>
    <parent link="link_2"/>
    <child link="link_3"/>
    <origin xyz="0 ${l2} 0 "/>
  </joint>

  <link name="link_4">
   <inertial>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <mass value="${m4}"/>
     <inertia ixx="1"  ixy="0"  ixz="0" iyy="1" iyz="0" izz="1" />
   </inertial>
    <visual>
      <geometry>
	      <cylinder length="${l4}" radius="0.05"/>
      </geometry>
      <material name="red"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
  </link>

  <joint name="joint_4" type="prismatic">
    <parent link="link_3"/>
    <child link="link_4"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="-0.2" upper="0.2" velocity="0.5"/>
    <origin xyz="0 0 ${-(base_height-l0)} "/>
  </joint>

  <link name="EndEffector">
   <inertial>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <mass value="0"/>
     <inertia ixx="0"  ixy="0"  ixz="0" iyy="0" iyz="0" izz="0" />
   </inertial>

    <visual>
      <geometry>
	  <box size="0.05 0.1 0.03"/>
      </geometry>
      <material name="green"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
  </link>

  <joint name="joint_5" type="fixed">
    <parent link="link_4"/>
    <child link="EndEffector"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>




</robot>
